### ISSUE TITLE
Create elevator pitch or advertisement for the project

### ISSUE THREAD

**Issue by vadeyem1** [LilitKarayan/Neutrack#4]
Team (@JordanBarron-cpu, @LilitKarayan, @vadeyem1)  will create an

- [x] elevator pitch or advertisement for the project
- [x] elevator pitch or advertisement for the project will be compiled to one video by @LilitKarayan

**Comment by JordanBarron-cpu** [comment]
A network-related or instance-specific error occurred while establishing a
connection to SQL Server. The server was not found or was not accessible.
Verify that the instance name is correct and that SQL Server is configured
to allow remote connections. (provider: TCP Provider, error: 0 - No
connection could be made because the target machine actively refused it.)
